AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  APP:
    Type: String
  UAI:
    Type: String
  ENV:
    Type: String
  serviceName:
    Type: String
  UpdateParameter:
    Type: String

  # Dummy parameters
  serviceSecret:
    Type: String
  scale:
    Type: String
  listenerArn:
    Type: String
  priority:
    Type: String
    Default: ""
  ECRImageTag:
    Type: String


  # For migration purpose
  serviceContext:
    Type: String

Resources:
  VPCLookupUtil:
    Type: Custom::VPCLookup
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'BHCHelperLambdaUtilities'
      method: vpc_lookup

  ECRRegistryService:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
     ProductName: "ECR-Registry"
     ProvisioningArtifactName: "{{resolve:ssm:/ServiceCatalog/ECR-Registry/LatestVersion:1}}"
     ProvisioningParameters:
      - Key: "AppName"
        Value: !Ref APP
      - Key: "Env"
        Value: !Ref ENV
      - Key: "ECRRepoName"
        Value: !Ref serviceName
      - Key: "UAI"
        Value: !Ref UAI
      - Key: "UpdateParameter"
        Value: !Ref UpdateParameter
